// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF-mvHTxAcQjAFwQyXs8I4nZaCBPZ2Ln4',
    appId: '1:16469689697:web:6b01f41b7a24e68718b120',
    messagingSenderId: '16469689697',
    projectId: 'haelin',
    authDomain: 'haelin.firebaseapp.com',
    storageBucket: 'haelin.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa0EoNI0TpW3Rt7ORwkR_u0Xg3ZnKV0fE',
    appId: '1:16469689697:android:f687a9e0f52c56cf18b120',
    messagingSenderId: '16469689697',
    projectId: 'haelin',
    storageBucket: 'haelin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs-BByLoOW1iaWaiP1JFFaY2s1SDBlUX0',
    appId: '1:16469689697:ios:3df1e2587bc3b54518b120',
    messagingSenderId: '16469689697',
    projectId: 'haelin',
    storageBucket: 'haelin.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs-BByLoOW1iaWaiP1JFFaY2s1SDBlUX0',
    appId: '1:16469689697:ios:3df1e2587bc3b54518b120',
    messagingSenderId: '16469689697',
    projectId: 'haelin',
    storageBucket: 'haelin.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCF-mvHTxAcQjAFwQyXs8I4nZaCBPZ2Ln4',
    appId: '1:16469689697:web:dfeb303ca622b46018b120',
    messagingSenderId: '16469689697',
    projectId: 'haelin',
    authDomain: 'haelin.firebaseapp.com',
    storageBucket: 'haelin.firebasestorage.app',
  );
}
